# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
    apt:
        packages:
            - libudunits2-dev
            - libproj-dev
            - libgeos-dev
            - libgdal-dev

before_install:
    - Rscript -e 'install.packages("remotes", repos="https://cran.rstudio.com")'
    - Rscript -e 'remotes::install_github("moveability/moveability")'
